---
- name: Install Certbot and Nginx plugin
  apt:
    name: 
      - certbot
      - python3-certbot-nginx
    state: present

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Obtain SSL certificate and configure Nginx
  command: >
    certbot --nginx 
    -d {{ domain_name }} 
    --non-interactive 
    --agree-tos 
    --email {{ certbot_email }}
    --redirect
    --hsts
    --staple-ocsp
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
  register: certbot_result
  changed_when: certbot_result.rc == 0
  notify: reload nginx

- name: Set up automatic renewal
  cron:
    name: "Certbot renewal"
    job: "certbot renew --quiet"
    minute: "0"
    hour: "0"
    day: "*/7"
    user: root
