---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - git
    state: present

- name: Add GitHub Actions public key
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK6KClPGKeWGiglv07e4TNdTNiJTP5JyOYtaJrNC13iK github-actions-deploy"